FUNCTION(find_files_matching_patterns output directory filter_masks)
	set( file_list )	
	foreach( filter_mask ${filter_masks} )
		file(GLOB_RECURSE found_files ${directory}/${filter_mask})
		list(APPEND file_list ${found_files})
		endforeach()
	set(${output} ${file_list} PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(__add_dependencies TARGET TARGET_DEPENDS TARGET_DEPENDS_NO_TARGET)
	foreach( dependency ${TARGET_DEPENDS} ) 
		if (NOT TARGET ${dependency})
			message(FATAL_ERROR "The dependency target \"${dependency}\" of target \"${TARGET}\" does not exist, please check and reorder the add_subdirectory() base on dependency")
		endif() 
		target_link_libraries(${TARGET} PUBLIC ${dependency})
	endforeach()
	foreach( dependency ${TARGET_DEPENDS_NO_TARGET} ) 
		target_link_libraries(${TARGET} PUBLIC ${dependency})
	endforeach()
ENDFUNCTION()

